name: Build Valhalla for Android aarch64

on:
  push:
    branches:
      - main  # Ganti dengan branch yang Anda inginkan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true  # Mengambil submodul

      - name: Set up Android NDK
        uses: actions/setup-android@v2
        with:
          ndk-version: '25.2.9519653'  # Ganti dengan versi NDK yang sesuai

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Verify Android SDK installation
        run: sdkmanager --list

      - name: Build Valhalla and Submodules
        run: |
          # Setup environment variables
          export ANDROID_NDK_HOME=$ANDROID_SDK/ndk/25.2.9519653
          export CMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake
          export TARGET_ABI=aarch64-v8a
          export API_LEVEL=28  # Ganti dengan API level yang Anda inginkan

          # Buat direktori build
          mkdir -p build-android && cd build-android

          # Konfigurasi dan build menggunakan CMake
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DANDROID_ABI=$TARGET_ABI \
            -DANDROID_PLATFORM=android-$API_LEVEL \
            -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE \
            -S ..  # Menunjuk ke root proyek

          # Jalankan build
          make -j$(nproc)

          # Menyimpan hasil build
          mkdir -p $HOME/artifacts
          cp -r *.so $HOME/artifacts/  # Mengcopy hasil build ke artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: valhalla-libs
          path: $HOME/artifacts/*
