name: Build Valhalla for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Specify the distribution

      - name: Install Android SDK and NDK
        run: |
          # Install required packages
          sudo apt-get update
          sudo apt-get install -y wget unzip

          # Download command line tools
          SDK_TOOLS_VERSION=8512546
          wget https://dl.google.com/android/repository/commandlinetools-linux-${SDK_TOOLS_VERSION}_latest.zip
          mkdir -p $HOME/Android/cmdline-tools
          unzip commandlinetools-linux-${SDK_TOOLS_VERSION}_latest.zip -d $HOME/Android/cmdline-tools
          rm commandlinetools-linux-${SDK_TOOLS_VERSION}_latest.zip

          # Move the tools into the correct location
          mv $HOME/Android/cmdline-tools/cmdline-tools $HOME/Android/cmdline-tools/latest

          # Set up environment variables
          echo "ANDROID_SDK=$HOME/Android" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK" >> $GITHUB_ENV
          echo "NDK_VERSION=25.2.9519653" >> $GITHUB_ENV

          # Install SDK and NDK using sdkmanager
          yes | $HOME/Android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK "platform-tools" "platforms;android-33" "ndk;25.2.9519653"

      - name: Set up environment variables
        run: |
          echo "NDK=$ANDROID_SDK/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "VALHALLA_DIR=$GITHUB_WORKSPACE/extProjects/valhalla" >> $GITHUB_ENV
          echo "TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64" >> $GITHUB_ENV

          # Add Clang to PATH
          echo "PATH=\$PATH:$TOOLCHAIN/bin" >> $GITHUB_ENV

      - name: Install required packages
        run: |
          sudo apt-get install -y cmake build-essential wget
